<template>
  <div class="container">
    <div class="row page-header">
      <div class="col-lg-12">
        <h3>Lab Sessions</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <a href="/createNewSession" class=
        "btn btn-sm btn-info">Add Session</a>
      </div>
      <div class="col-md-6">
        <lab-filter></lab-filter>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Lab Code</th>
              <th>Lab Name</th>
              <th class="center-align-table-cell">Session
              Number</th>
              <th class="center-align-table-cell">Start Date</th>
              <th class="center-align-table-cell">get
              Details</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
import LabFilter from "./LabFilter.vue";
import axios from 'axios';


export default {
  data() {
    return {  labSessions : []
    }
  },
  components: {
    LabFilter
  },
  methods: {
    getLabSessions: function() {

      var errorMsgText;
      var errorMsgObj;
      var i;
      var msg = {
        method: 'get',
        url: '/api/getLabSessionsOverview',
        data: {}
      }

      axios(msg)
        .then((response) => {
          console.log("RESPONSE ", response.data.labSessions);
          if (response.data.labSessions ){
            this.labSessions = response.data.labSessions;
          }
        })
        .catch((error) => {
          if (error.response) {
            // The request was made and the server responded with a status code
            // that falls out of the range of 2xx
            errorMsgText = '';
            // is error is known, generated by API. 500 level are sql errors and
            // could come with an array of errors, but usually only one.
            if ((error.response.status === 500) && (error.response.data.errors)) {
              for (i = 0; i < error.response.data.errors.length; ++i) {
                context.commit('pushlookupInformationErrors', error.response.data.errors[i]);
              }
            } else if ((error.response.status === 400) && (error.response.data.message)) {
              errorMsgText += error.response.data.message;
              errorMsgObj = errorMsgs.createSimpleErrorMsg(errorMsgText, "Danger");
              context.commit('pushlookupInformationErrors', errorMsgObj);
            } else { // not known from the API
              errorMsgText += "Error";
              if (error.response.status) {
                errorMsgText += " status = " + error.response.status;
              }
              if (error.response.statusText) {
                errorMsgText += " " + error.response.statusText;
              }
              errorMsgObj = errorMsgs.createSimpleErrorMsg(errorMsgText, "Danger");
              context.commit('pushlookupInformationErrors', errorMsgObj);
            }



          } else if (error.request) {
            // The request was made but no response was received
            // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
            // http.ClientRequest in node.js
            //console.log('error.request', error.request);
            errorMsgObj = errorMsgs.createSimpleErrorMsg("The request was made but no response was received", "Danger")
            context.commit('pushlookupInformationErrors', errorMsgObj);

          } else {
            // Something happened in setting up the request that triggered an Error
            console.log('error.message', error.message);
            errorMsgObj = errorMsgs.createSimpleErrorMsg("An error was thrown and caught handling API request", "Danger");
            context.commit('pushlookupInformationErrors', errorMsgObj);

          }
        });
    }
  },
  created() {
    this.getLabSessions();  // if we are at the login page, no user data should be saved
  }
}
</script>
